name: Process All JPG Images

on:
  push:
    branches:
      - main

jobs:
  process-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install pillow torch transformers numpy

      - name: Process all JPG images
        run: |
          echo "Starting image processing..."
          for image in $(find ./images -type f -iname "*.jpg"); do
            echo "Processing $image"
            python process_image.py "$image"
          done

      - name: Debug images.json
        run: |
          echo "Contents of images.json after processing:"
          cat images.json || echo "images.json not found!"

      - name: Commit and push changes
        run: |
          echo "Committing changes..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images.json
          git diff --quiet && echo "No changes to commit" || git commit -m "Update images.json with processed images"
          git push || echo "No changes to push"
