name: Update Images JSON

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Generate images.json
    - name: Generate images.json
      run: |
        # Define the base URL for the images
        BASE_URL="http://openimg.saltyaus.space/images"
        
        # Navigate to the images folder
        IMAGES_DIR="images" # Ensure this matches your repository structure
        JSON_FILE="images.json"
        echo "[]" > $JSON_FILE # Initialize JSON file

        # Generate JSON content
        echo "[" > $JSON_FILE
        for category in $(find $IMAGES_DIR -mindepth 1 -type d -exec basename {} \;); do
          for image in $(find $IMAGES_DIR/$category -type f -name "*.jpg" -exec basename {} \;); do
            echo "  {" >> $JSON_FILE
            echo "    \"url\": \"$BASE_URL/$category/$image\"," >> $JSON_FILE
            echo "    \"name\": \"$(basename $image .jpg)\"," >> $JSON_FILE
            echo "    \"category\": \"$category\"" >> $JSON_FILE
            echo "  }," >> $JSON_FILE
          done
        done
        sed -i '$ s/,$//' $JSON_FILE # Remove trailing comma
        echo "]" >> $JSON_FILE

    # Step 3: Commit and push the changes
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "SaltyBot[bot]"
        git config --global user.email "bots@salty.cool"
        git add images.json
        git commit -m "images.json autoupdate"
        git push
