name: Generate Images JSON

on:
  push:    # Runs on every push
    branches:
      - main
  workflow_dispatch:  # Allows for manual trigger

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate images.json
        run: |
          IMAGES_DIR="images"
          JSON_FILE="images.json"
          BASE_URL="http://openimg.saltyaus.space/images"
          
          echo "[" > $JSON_FILE
          find $IMAGES_DIR -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.jpeg" \) | while read image_path; do
            CATEGORY=$(basename $(dirname "$image_path"))
            IMAGE_NAME=$(basename "$image_path")
            TITLE=$(basename "$IMAGE_NAME" | sed 's/\.[^.]*$//') # Extract name without extension
            echo "  {" >> $JSON_FILE
            echo "    \"url\": \"$BASE_URL/$CATEGORY/$IMAGE_NAME\"," >> $JSON_FILE
            echo "    \"name\": \"$TITLE\"," >> $JSON_FILE
            echo "    \"category\": \"$CATEGORY\"" >> $JSON_FILE
            echo "  }," >> $JSON_FILE
          done
          sed -i '$ s/,$//' $JSON_FILE # Remove trailing comma
          echo "]" >> $JSON_FILE

      - name: Commit and Push JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images.json
          git commit -m "Update images.json with latest image files"
          git push

      - name: Trigger static.yml workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"trigger_static_workflow"}'
