name: Generate Images JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bash

      - name: Run bash script to generate images.json
        run: |
          chmod +x ./generate_images.sh
          ./generate_images.sh

      - name: Commit and Push JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images.json
          git commit -m "Update images.json with latest image files"
          git push

      - name: Trigger static.yml workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"trigger_static_workflow"}'
