name: Add New Images to JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up dependencies
      - name: Set up Bash and Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Step 3: Run the script to update images.json
      - name: Update images.json
        run: |
          chmod +x ./update_images.sh
          ./update_images.sh

      # Step 4: Commit and push the updated JSON file
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images.json
          git diff --quiet || git commit -m "Update images.json with new images"
          git push || echo "No changes to push"
