name: Update Images and Generate JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python and install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install torch torchvision transformers pillow

      # Step 3: Run the script to update images.json
      - name: Update images.json
        run: |
          chmod +x ./update_images.sh
          ./update_images.sh

      # Step 4: Commit and Push Changes (images.json only)
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Stage only the images.json file
          git add images.json

          # Commit changes if there are any
          git diff --cached --quiet || git commit -m "Update images.json with new images"

          # Push changes
          git push || echo "No changes to push"
