name: Generate images.json

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Bash and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq # Optional for more advanced JSON handling

      - name: Generate images.json
        run: |
          # Define the base URL and image structure
          BASE_URL="http://openimg.saltyaus.space/images"
          IMAGES_DIR="images"
          JSON_FILE="images.json"

          # Run the JSON generation script
          echo "[" > $JSON_FILE
          FIRST_ENTRY=true
          for category in $(find $IMAGES_DIR -mindepth 1 -type d -exec basename {} \;); do
            for image in $(find $IMAGES_DIR/$category -type f -name "*.jpg" -exec basename {} \;); do
              if [ "$FIRST_ENTRY" = true ]; then
                FIRST_ENTRY=false
              else
                echo "," >> $JSON_FILE
              fi
              echo "  {" >> $JSON_FILE
              echo "    \"url\": \"$BASE_URL/$category/$image\"," >> $JSON_FILE
              echo "    \"name\": \"$(basename "$image" .jpg)\"," >> $JSON_FILE
              echo "    \"category\": \"$category\"" >> $JSON_FILE
              echo "  }" >> $JSON_FILE
            done
          done
          echo "]" >> $JSON_FILE
          echo "images.json generated successfully."

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add images.json
          git diff --quiet || git commit -m "Update images.json with new images"
          git push || echo "No changes to push"
