name: Image Upload and Processing

on:
  push:
    paths:
      - "images/**"  # Trigger this workflow when an image file is pushed to the "images" folder

jobs:
  process-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest stable version of Python

      - name: Install required dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision transformers  # Install necessary libraries for image processing

      - name: Extract image filename from commit
        id: extract_image_name
        run: |
          # Extract the image file name from the commit
          IMAGE_NAME=$(git diff --name-only $GITHUB_SHA^..$GITHUB_SHA | grep -o 'images/.*')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "Image file: $IMAGE_NAME"

      - name: Process the image with Python script
        run: |
          python process_image.py $IMAGE_NAME

