name: Generate Image Descriptions

on:
  push:
    paths:
      - 'images/**'  # Run on image uploads to the 'images' folder

jobs:
  image_captioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision transformers Pillow

    - name: Download BLIP model
      run: |
        git clone https://github.com/salesforce/BLIP.git
        cd BLIP
        pip install -r requirements.txt

    - name: Generate caption for new image
      run: |
        cd BLIP
        python generate_caption.py --image_path="../images/my_image.jpg"

    - name: Commit new description
      run: |
        echo "Generated caption for new image" > description.txt
        git add description.txt
        git commit -m "Add description for new image"
        git push
