name: Process Image Manually

on:
  workflow_dispatch:  # Triggered manually from the GitHub Actions interface

jobs:
  process-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install pillow

      - name: Run image processing script
        run: |
          python process_image.py $IMAGE_NAME
