name: Process Image Manually

on:
  workflow_dispatch:
    inputs:
      category:
        description: 'Category of the image (e.g., nature, animals)'
        required: true
        default: 'nature'  # Default category, can be changed manually
      image_name:
        description: 'The name of the image to process (e.g., 1.jpg)'
        required: true
        default: 'image.jpg'  # Default image name, can be changed manually

jobs:
  process-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install pillow torch transformers numpy  # Install Pillow, PyTorch, Transformers, and NumPy

      - name: Run image processing script
        run: |
          # Combine category and image name into the full path
          IMAGE_PATH="images/${{ github.event.inputs.category }}/${{ github.event.inputs.image_name }}"
          python process_image.py $IMAGE_PATH
